//------------------------------------------------------------
// Auto-generated by QuickBind. Do not edit manually.
//------------------------------------------------------------
using UnityEngine;

namespace EmojiWar.GameMain.UI
{
public partial class BackpackForm
{
    [SerializeField] private UnityEngine.UI.Text m_TxtTitle = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnCollapse = null;

    /// <summary>由 QuickBind 生成：应用绑定引用。</summary>
    public void QuickBindApplyBindings(EmojiWar.GameMain.UI.QuickBind bind)
    {
        var go_m_TxtTitle = bind.GetTarget("m_TxtTitle");
        if (go_m_TxtTitle != null)
        {
            m_TxtTitle = go_m_TxtTitle.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_BtnCollapse = bind.GetTarget("m_BtnCollapse");
        if (go_m_BtnCollapse != null)
        {
            m_BtnCollapse = go_m_BtnCollapse.GetComponent<UnityEngine.UI.Button>();
        }
    }
}
}
