//------------------------------------------------------------
// Auto-generated by QuickBind. Do not edit manually.
//------------------------------------------------------------
using UnityEngine;

namespace EmojiWar.GameMain.UI
{
public partial class BattleHudForm
{
    [SerializeField] private UnityEngine.UI.Text m_TxtCoin = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtWave = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnSettings = null;
    [SerializeField] private UnityEngine.UI.Image m_ImgWeaponIcon = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtWeaponName = null;

    /// <summary>由 QuickBind 生成：应用绑定引用。</summary>
    public void QuickBindApplyBindings(EmojiWar.GameMain.UI.QuickBind bind)
    {
        var go_m_TxtCoin = bind.GetTarget("m_TxtCoin");
        if (go_m_TxtCoin != null)
        {
            m_TxtCoin = go_m_TxtCoin.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtWave = bind.GetTarget("m_TxtWave");
        if (go_m_TxtWave != null)
        {
            m_TxtWave = go_m_TxtWave.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_BtnSettings = bind.GetTarget("m_BtnSettings");
        if (go_m_BtnSettings != null)
        {
            m_BtnSettings = go_m_BtnSettings.GetComponent<UnityEngine.UI.Button>();
        }
        var go_m_ImgWeaponIcon = bind.GetTarget("m_ImgWeaponIcon");
        if (go_m_ImgWeaponIcon != null)
        {
            m_ImgWeaponIcon = go_m_ImgWeaponIcon.GetComponent<UnityEngine.UI.Image>();
        }
        var go_m_TxtWeaponName = bind.GetTarget("m_TxtWeaponName");
        if (go_m_TxtWeaponName != null)
        {
            m_TxtWeaponName = go_m_TxtWeaponName.GetComponent<UnityEngine.UI.Text>();
        }
    }
}
}
