//------------------------------------------------------------
// Auto-generated by QuickBind. Do not edit manually.
//------------------------------------------------------------
using UnityEngine;

namespace EmojiWar.GameMain.UI
{
public partial class CharacterDockForm
{
    [SerializeField] private UnityEngine.UI.Text m_TxtSelectTitle = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnCollapse = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnChar1 = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnChar2 = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnChar3 = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnChar4 = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtChar1Name = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtChar2Name = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtChar3Name = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtChar4Name = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtDetailIcon = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtDetailName = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtDetailDesc = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtDetailStats = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtCurrentChar = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnTab = null;

    /// <summary>由 QuickBind 生成：应用绑定引用。</summary>
    public void QuickBindApplyBindings(EmojiWar.GameMain.UI.QuickBind bind)
    {
        var go_m_TxtSelectTitle = bind.GetTarget("m_TxtSelectTitle");
        if (go_m_TxtSelectTitle != null)
        {
            m_TxtSelectTitle = go_m_TxtSelectTitle.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_BtnCollapse = bind.GetTarget("m_BtnCollapse");
        if (go_m_BtnCollapse != null)
        {
            m_BtnCollapse = go_m_BtnCollapse.GetComponent<UnityEngine.UI.Button>();
        }
        var go_m_BtnChar1 = bind.GetTarget("m_BtnChar1");
        if (go_m_BtnChar1 != null)
        {
            m_BtnChar1 = go_m_BtnChar1.GetComponent<UnityEngine.UI.Button>();
        }
        var go_m_BtnChar2 = bind.GetTarget("m_BtnChar2");
        if (go_m_BtnChar2 != null)
        {
            m_BtnChar2 = go_m_BtnChar2.GetComponent<UnityEngine.UI.Button>();
        }
        var go_m_BtnChar3 = bind.GetTarget("m_BtnChar3");
        if (go_m_BtnChar3 != null)
        {
            m_BtnChar3 = go_m_BtnChar3.GetComponent<UnityEngine.UI.Button>();
        }
        var go_m_BtnChar4 = bind.GetTarget("m_BtnChar4");
        if (go_m_BtnChar4 != null)
        {
            m_BtnChar4 = go_m_BtnChar4.GetComponent<UnityEngine.UI.Button>();
        }
        var go_m_TxtChar1Name = bind.GetTarget("m_TxtChar1Name");
        if (go_m_TxtChar1Name != null)
        {
            m_TxtChar1Name = go_m_TxtChar1Name.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtChar2Name = bind.GetTarget("m_TxtChar2Name");
        if (go_m_TxtChar2Name != null)
        {
            m_TxtChar2Name = go_m_TxtChar2Name.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtChar3Name = bind.GetTarget("m_TxtChar3Name");
        if (go_m_TxtChar3Name != null)
        {
            m_TxtChar3Name = go_m_TxtChar3Name.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtChar4Name = bind.GetTarget("m_TxtChar4Name");
        if (go_m_TxtChar4Name != null)
        {
            m_TxtChar4Name = go_m_TxtChar4Name.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtDetailIcon = bind.GetTarget("m_TxtDetailIcon");
        if (go_m_TxtDetailIcon != null)
        {
            m_TxtDetailIcon = go_m_TxtDetailIcon.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtDetailName = bind.GetTarget("m_TxtDetailName");
        if (go_m_TxtDetailName != null)
        {
            m_TxtDetailName = go_m_TxtDetailName.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtDetailDesc = bind.GetTarget("m_TxtDetailDesc");
        if (go_m_TxtDetailDesc != null)
        {
            m_TxtDetailDesc = go_m_TxtDetailDesc.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtDetailStats = bind.GetTarget("m_TxtDetailStats");
        if (go_m_TxtDetailStats != null)
        {
            m_TxtDetailStats = go_m_TxtDetailStats.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtCurrentChar = bind.GetTarget("m_TxtCurrentChar");
        if (go_m_TxtCurrentChar != null)
        {
            m_TxtCurrentChar = go_m_TxtCurrentChar.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_BtnTab = bind.GetTarget("m_BtnTab");
        if (go_m_BtnTab != null)
        {
            m_BtnTab = go_m_BtnTab.GetComponent<UnityEngine.UI.Button>();
        }
    }
}
}
