//------------------------------------------------------------
// Auto-generated by QuickBind. Do not edit manually.
//------------------------------------------------------------
using UnityEngine;

namespace EmojiWar.GameMain.UI
{
public partial class RoomForm
{
    [SerializeField] private UnityEngine.UI.Text m_TxtTitle = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtPlayerList = null;
    [SerializeField] private UnityEngine.UI.Text m_TxtStatus = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnReady = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnChangeChar = null;
    [SerializeField] private UnityEngine.UI.Button m_BtnLeave = null;

    /// <summary>由 QuickBind 生成：应用绑定引用。</summary>
    public void QuickBindApplyBindings(EmojiWar.GameMain.UI.QuickBind bind)
    {
        var go_m_TxtTitle = bind.GetTarget("m_TxtTitle");
        if (go_m_TxtTitle != null)
        {
            m_TxtTitle = go_m_TxtTitle.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtPlayerList = bind.GetTarget("m_TxtPlayerList");
        if (go_m_TxtPlayerList != null)
        {
            m_TxtPlayerList = go_m_TxtPlayerList.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_TxtStatus = bind.GetTarget("m_TxtStatus");
        if (go_m_TxtStatus != null)
        {
            m_TxtStatus = go_m_TxtStatus.GetComponent<UnityEngine.UI.Text>();
        }
        var go_m_BtnReady = bind.GetTarget("m_BtnReady");
        if (go_m_BtnReady != null)
        {
            m_BtnReady = go_m_BtnReady.GetComponent<UnityEngine.UI.Button>();
        }
        var go_m_BtnChangeChar = bind.GetTarget("m_BtnChangeChar");
        if (go_m_BtnChangeChar != null)
        {
            m_BtnChangeChar = go_m_BtnChangeChar.GetComponent<UnityEngine.UI.Button>();
        }
        var go_m_BtnLeave = bind.GetTarget("m_BtnLeave");
        if (go_m_BtnLeave != null)
        {
            m_BtnLeave = go_m_BtnLeave.GetComponent<UnityEngine.UI.Button>();
        }
    }
}
}
